# HOWTO: https://pre-commit.com/#usage
# pip3 install pre-commit
# pre-commit install -t pre-commit -t pre-push

exclude: ^frontend/src/routeTree.gen.ts$
repos:
  - repo: https://github.com/psf/black
    rev: c6755bb741b6481d6b3d3bb563c83fa060db96c9  # frozen: 26.3.1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/biomejs/pre-commit
    rev: "5e71eb16415bb412e2e88eeea7348d6f9c780d25"  # frozen: v2.4.15
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.8.3"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # - repo: https://github.com/motet-a/jinjalint
  #   rev: 01e0a4d8f1ee775aee00eb9d715eff2b4cc49e4d
  #   hooks:
  #     - id: jinjalint
  #       types: [file]
  #       files: \.(html)$
  #       args:
  #         - --parse-only
  - repo: https://github.com/PyCQA/flake8
    rev: d93590f5be797aabb60e3b09f2f52dddb02f349f  # frozen: 7.3.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=100
          - --per-file-ignores=packit_dashboard/packit_dashboard.wsgi:F401,E402
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: d2823d321df3af8f878f7ee3414dc94d037145b9  # frozen: v2.1.0
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies: [types-requests, types-Flask, types-cachetools]

  - repo: https://github.com/packit/pre-commit-hooks
    rev: ce4b530e5913c1b8651127ace81996464975ef48  # frozen: v1.3.0
    hooks:
      - id: check-rebase
        args:
          - https://github.com/packit/dashboard.git
        stages: [manual, pre-push]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 943377262562a12b57292fc98fabd7dbf81451fe  # frozen: 0.37.2
    hooks:
      - id: check-github-workflows
        args: ["--verbose"]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: ad1b27d73581aa16cca06fc4a0761fc563ffe8e8  # frozen: v1.5.6
    hooks:
      - id: insert-license
        name: insert-license-python
        types:
          - python
        args:
          - --license-filepath
          - LICENSE_HEADER.txt
          - --comment-style
          - "#"
      - id: insert-license
        name: insert-license-frontend
        types_or:
          - javascript
          - jsx
          - ts
          - tsx
        args:
          - --license-filepath
          - LICENSE_HEADER.txt
          - --comment-style
          - "//"
