name: Test frontend
on:
  push:
    branches:
      - main
      - stable
  pull_request:
  workflow_dispatch:

jobs:
  run-vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: pnpm/action-setup@f40ffcd9367d9f12939873eb1018b921a783ffaa # v4
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install and Build
        run: |
          (cd frontend && pnpm install);
          make .install-logos
          API_URL="https://prod.packit.dev/api" make transpile-prod

      - name: Run Vitest
        run: make test-frontend-coverage
